### PR TITLE
fix: generate doc for getters

### LINKED ISSUE #1548: TypeScript include documentation for properties instead of getters
#### Reason/Context
Setting the description on private properties does not show up on auto completion. See this: https://modelina.org/playground?tsIncludeDescriptions=true

#### Description
Instead the code should be:

```

class LightMeasured {
  private _id?: number;
  private _lumens?: number;
  private _sentAt?: string;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    id?: number,
    lumens?: number,
    sentAt?: string,
    additionalProperties?: Map<string, any>,
  }) {
    this._id = input.id;
    this._lumens = input.lumens;
    this._sentAt = input.sentAt;
    this._additionalProperties = input.additionalProperties;
  }

  /**
   * Id of the streetlight.
   */
  get id(): number | undefined { return this._id; }
  set id(id: number | undefined) { this._id = id; }

  /**
   * Light intensity measured in lumens.
   */
  get lumens(): number | undefined { return this._lumens; }
  set lumens(lumens: number | undefined) { this._lumens = lumens; }

  /**
   * Date and time when the message was sent.
   */
  get sentAt(): string | undefined { return this._sentAt; }
  set sentAt(sentAt: string | undefined) { this._sentAt = sentAt; }

  get additionalProperties(): Map<string, any> | undefined { return this._additionalProperties; }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) { this._additionalProperties = additionalProperties; }
}
module.exports = LightMeasured;
```

### PR DESCRIPTION
**Pull request by akkshitgupta**
## Description
This pull request corrects the generated code docs to their expected position.

| Earlier | Now |
| --- | --- |
| Screenshot-1|Screenshot-2|

## Related Issue 
Fixes #1548 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by akkshitgupta** [comment]
Hey @Samridhi-98 can you please review this pull request. Thank You 😄

File: src/generators/typescript/presets/DescriptionPreset.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export const TS_DESCRIPTION_PRESET: TypeScriptPreset = {
     self({ renderer, model, content }) {
       return renderDescription({ renderer, content, item: model });
     },
-    property({ renderer, property, content }) {
```
Comment (jonaslagoni) [inline src/generators/typescript/presets/DescriptionPreset.ts:40]: We need to make it slightly more advanced, and use the options argument to conditionally write docs for properties or getters depending on whether the option for using getters is sat 🙂

Comment (akkshitgupta) [reply src/generators/typescript/presets/DescriptionPreset.ts:40]: > Sorry for the late reply @akkshitgupta 🙇

I understand that you are occupied with your work as well. Thank you for being helpful as it encourages me to accept more challenges and continue my journey with AsyncAPI.


> does not matter if there are duplicate information for now.
I would like to solve it out rather than just allowing the duplicates if it not much necessary to include description for getters and hold up the PR for now. LMK WDYT

Comment (jonaslagoni) [reply src/generators/typescript/presets/DescriptionPreset.ts:40]: I am getting so confused with all these PRs targeting different languages where some use getters and setters automatically and others have options to turn them on and off..

For TypeScript it's always on and can't be turned off... So your implementation is excellent 😄

**Review by jonaslagoni — APPROVED** [review]
Sorry for taking this long to end up with nothing but smoke 🙇

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 do you have time to take a look :v:

**Comment by sambhavgupta0705** [comment]
Yes for sure
I will review this soon

**Review by Samridhi-98 — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@all-contributors please add @akkshitgupta for code, bugs
