### PR TITLE
fix(website): fix broken open graph images

### LINKED ISSUE #1165: [Website] Broken OG images
#### Describe the bug
The OG (Open Graph) images are broken. 

That means sharing the website URL on social media won't have images as previews.

See the following meta tag on the [Modelina website source code](view-source:https://modelina.org):

```html
<meta property="og:url" content="https://master--modelina.netlify.app/"/><meta property="og:image" content="https://master--modelina.netlify.app/img/social/modelina-card.jpg"/>
```

As you can check, the link is broken.

### PR DESCRIPTION
**Pull request by jerensl**
## Description
Images in HeadComponents is not the actual folder where the images have been put in

## Related Issue
Fixes #1165

### CODE REVIEW

File: modelina-website/src/components/layouts/Head.tsx [hunk 1]
```diff
@@ -18,9 +18,9 @@ export interface HeadProps {
 export default function HeadComponent({
   title,
   description = 'Open source tools to easily build and maintain your event-driven architecture. All powered by the AsyncAPI specification, the industry standard for defining asynchronous APIs.',
-  image = '/img/social/website-card.jpg'
+  image = '/img/card/website-card.jpg'
 }: HeadProps) {
-  const url = process.env.DEPLOY_PRIME_URL || process.env.DEPLOY_URL;
+  const url = 'https://modelina.org';
```
Comment (devilkiller-ag) [inline modelina-website/src/components/layouts/Head.tsx:23]: We can set an environment variable for this instead of directly mentioning it here and use it as it was used earlier.

cc: @jonaslagoni

Comment (jerensl) [reply modelina-website/src/components/layouts/Head.tsx:23]: @devilkiller-ag Make sure to start with NEXT_PUBLIC_ , if you want to include the environment variable on the bundle during the build time

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

Comment (jonaslagoni) [reply modelina-website/src/components/layouts/Head.tsx:23]: 👍

Comment (devilkiller-ag) [reply modelina-website/src/components/layouts/Head.tsx]: I have added the environment variable on the Netlify.

**Review by devilkiller-ag — APPROVED** [review]
